{% set name = "temporalio" %}
{% set version = "1.18.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/temporalio-{{ version }}.tar.gz
  sha256: 46394498f8822e61b3ce70d6735de7618f5af0501fb90f3f90f4b4f9e7816d77

build:
  skip: true  # [win]
  script:
    - {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    - cd temporalio/bridge
    - cargo-bundle-licenses --format yaml --output THIRDPARTY.yml
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - maturin >=1.0,<2.0                     # [build_platform != target_platform]
    - cargo-bundle-licenses
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('rust') }}
    - libprotobuf
  host:
    - python
    - maturin >=1.0,<2.0
    - pip
  run:
    - python
    - nexus-rpc ==1.1.0
    - protobuf >=3.20,<7
    - python-dateutil >=2.8.2,<3  # [py<311]
    - types-protobuf >=3.20
    - typing_extensions >=4.2.0,<5

test:
  imports:
    - temporalio
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/temporalio/sdk-python
  summary: Temporal.io Python SDK
  license: MIT
  license_file:
    - LICENSE
    - temporalio/bridge/THIRDPARTY.yml
    - temporalio/bridge/sdk-core/LICENSE.txt
    - temporalio/bridge/sdk-core/sdk-core-protos/protos/api_cloud_upstream/LICENSE
    - temporalio/bridge/sdk-core/sdk-core-protos/protos/api_upstream/LICENSE
    - temporalio/bridge/sdk-core/fsm/LICENSE.txt
    - temporalio/bridge/sdk-core/fsm/rustfsm_trait/LICENSE.txt
    - temporalio/bridge/sdk-core/fsm/rustfsm_procmacro/LICENSE.txt

extra:
  recipe-maintainers:
    - chrisjryan
    - dgasmith
    - nic-chira
    - fzding
